# Generated by Django 4.2.19 on 2025-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epos_name', models.CharField(max_length=100, unique=True)),
                ('epos_photo', models.ImageField(blank=True, null=True, upload_to='epos/', verbose_name='Фото эпоса')),
                ('epos_description', models.CharField(max_length=250)),
                ('epos_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Эпос',
                'verbose_name_plural': 'Эпосы',
            },
        ),
        migrations.CreateModel(
            name='Manaschi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manaschi_name', models.CharField(max_length=100)),
                ('manaschi_photo', models.ImageField(blank=True, null=True, upload_to='manaschi/', verbose_name='Фото манасчи')),
                ('manaschi_description', models.CharField(max_length=250)),
                ('manaschi_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Манасчи',
                'verbose_name_plural': 'Манасчи',
            },
        ),
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('researchers_photo', models.ImageField(blank=True, null=True, upload_to='researchers/', verbose_name='Фото исследователей или этнографов')),
                ('researchers_description', models.CharField(max_length=250)),
                ('researchers_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Исследователь',
                'verbose_name_plural': 'Исследователи',
            },
        ),
    ]
